[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
protocol = { path = "../protocol" }
tokio = { version = "1.48.0", features = ["full"] }
bincode = "1.3.3"
x25519-dalek = { version = "2.0.1", features = ["serde", "static_secrets"] }
hex = "0.4.3"
